### PR TITLE
Add new property omdb.plot

### PR DESCRIPTION
**Pull request by Angelinas1**
Marcel this will be New Plot for PVR,
 If I have Kodi Label Plot ,
SkinHelper.ListItem.Plot will show only plot from EPG.
This Plot will be on Kodi language..not like language from EPG
 (I use multi language EPG).
All Plot be on same language, and different from EPG  :)

### CODE REVIEW

**Comment by marcelveldt** [comment]
makes sense but please change the key from omdb.plot to imdb.plot
the plot provided by omdb is from IMDB... OMDB is only the service in between

**Comment by marcelveldt** [comment]
elif key == "Plot":
    result["imdb.plot"] = value
     result["plot"] = value

**Comment by marcelveldt** [comment]
Sorry, you probably missed my comment. For the sake of completeness please also add the normal plot key. That way the plot key will be filled if it was empty in Kodi.

**Comment by Angelinas1** [comment]
Ok ...close this PR...You always know better, you change :)
TNX

**Comment by marcelveldt** [comment]
OK, will do. Thanks!

**Comment by marcelveldt** [comment]
FYI: Just checked in the change

**Pull request closed without merging**
