### PR TITLE
Changing logic "music_art_download_custom"

### PR DESCRIPTION
**Pull request by Angelinas1**
Mine way, working as should..
Extrafanart and rest of art in artist folder.
Album folder is in Artist folder with all art for album.

### CODE REVIEW

**Comment by Angelinas1** [comment]
Marcel, no need to include this PR
You doo on your way :)

**Comment by marcelveldt** [comment]
Just checked in some changes. This should fix the creation of the custom folders.
Also added the additional splitters.
Please test with latest git version and let me know.

**Comment by Angelinas1** [comment]
Sorry cant test...have error for fanart api (now is down)
All helper script is slow as "Belgrade Metro"...:)

> File "C:\Users\TEST\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 479, in send
                                                raise ConnectTimeout(e, request=request)

>

**Comment by marcelveldt** [comment]
Hmm looks like fanarttv is down indeed. Please test when it's back up, can't tell for sure how it all responds if that is down

**Comment by Angelinas1** [comment]
Not good your code without Fanart, Just try mine code same situation, and working.
Isue dont cose missing of fanart api...somthing in your code.
Try mine version of "musicartwork.py"...Collect all art in custom folder, but in log I have error
`18:18:05.941 T:3424   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Documents and Settings\TEST\My Documents\Downloads\Film\Music\1Art\Madonna\
18:18:15.143 T:3424   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Documents and Settings\TEST\My Documents\Downloads\Film\Music\1Art\Sexual `Exposure\`
Script try to load beffore is populated folder..
Just to be clear In mine Custom folder I have this "folder name" and art inside.

**Pull request closed without merging**
