### PR TITLE
Fix broken personal OMDB key option

### PR DESCRIPTION
**Pull request by sualfred**
explains itself :)

### CODE REVIEW

**Comment by Angelinas1** [comment]
Why repeat ?...I propsed same Pull request before 22 days

**Comment by sualfred** [comment]
@Angelinas1 
There is no open PR from you and I did not noticed the change in your fork. Guess you just forgot to submit the PR correctly.

**Comment by sualfred** [comment]
Now I saw it as a sub-commit of another PR. You should use cleaner and single PRs for different issues and improvements. Otherwise there will be a high chance that the maintainer - or other guys like me - won't notice it.

Nevertheless, both PRs will solve the issue.

**Comment by Angelinas1** [comment]
you have right,just change title for pr.7

**Comment by sualfred** [comment]
Closed, because the other PR has been merged.

**Pull request closed without merging**
