### PR TITLE
ExtraPoster support

### PR DESCRIPTION
**Pull request by amillogical**

### CODE REVIEW

**Comment by Angelinas1** [comment]
Are you shure that this workinkg ?
`Window(Home).Property(SkinHelper.ListItem.Art.ExtraPoster)`
I use `Window(Home).Property(SkinHelper.ListItem.Art.Posters)` and this working...
Why need new Property, plain to make download all poster in media folder ?

**Comment by marcelveldt** [comment]
I think this is meant to be an alternative for extrafanart, so you can have rotating posters

**Comment by Angelinas1** [comment]
ok , but Window(Home).Property(SkinHelper.ListItem.Art.Posters) works fine as multiimage

**Comment by amillogical** [comment]
@Angelinas1 Window(Home).Property(SkinHelper.ListItem.Art.ExtraPoster is working, I'm currently using it [here](https://gitlab.com/RealJohnGalt/skin.fuse.shifted/commit/9f261714b142ba4af270db6450cb9f2f4e95b0d0)

I wasn't aware I could use SkinHelper.ListItem.Art.Posters as multiimage. How are you storing those poster images?

**Comment by Angelinas1** [comment]
Script don't download posters, create cache images and you can find in simple cache.db
Images are from https://fanart.tv/ (random)

For me dont working :(
Are four your changes need to have in mine media folder   : /extraposter/poster0.poster1,poster2...
I don'have.....does I need to download mannual this Art ?
If this is condition to show Multiimage poster, then better is to Wait Marcel to create Automatic download posters in media folder...this work for music Art(AlbumArt)

**Comment by amillogical** [comment]
@Angelinas1, yes, it's the same as extrafanart currently. I've added the basic support in my library management software (emby) and setup downloading posters to the folders just as with emby's current extrafanart support.

**Comment by amillogical** [comment]
Thank you @Angelinas1 I missed that download functionality that exists for extrafanart already.

**Comment by marcelveldt** [comment]
I've decided to merge this in, I think it's a pretty valid addition and the code doesn't harm anyone.
@amillogical thanks for your contribution!

**Pull request merged**
